backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "foldingCrate"
    label: "Folding Crate"
    folder: "src/pages/folding-crates"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "foldingcrate-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "External long", name: "external_long", widget: "string"}
      - {label: "External width", name: "external_width", widget: "string"}
      - {label: "External height", name: "external_height", widget: "string"}
      - {label: "Internal long", name: "internal_long", widget: "string"}
      - {label: "Internal width", name: "internal_width", widget: "string"}
      - {label: "Internal height", name: "internal_height", widget: "string"}
      - {label: "Folded height", name: "folded_height", widget: "string"}
      - {label: "Volumn", name: "volumn", widget: "string"}
      - {label: "Weight", name: "weight", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Images", name: images, widget: list, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "movingCrate"
    label: "Moving Crate"
    folder: "src/pages/moving-crates"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "movingcrate-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "External long", name: "external_long", widget: "string"}
      - {label: "External width", name: "external_width", widget: "string"}
      - {label: "External height", name: "external_height", widget: "string"}
      - {label: "Internal long", name: "internal_long", widget: "string"}
      - {label: "Internal width", name: "internal_width", widget: "string"}
      - {label: "Internal height", name: "internal_height", widget: "string"}
      - {label: "Volumn", name: "volumn", widget: "string"}
      - {label: "Weight", name: "weight", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Images", name: images, widget: list, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "euroStackingContainer"
    label: "Euro Stacking Container"
    folder: "src/pages/euro-stacking-containers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "eurostackingcontainer-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "External long", name: "external_long", widget: "string"}
      - {label: "External width", name: "external_width", widget: "string"}
      - {label: "External height", name: "external_height", widget: "string"}
      - {label: "Internal long", name: "internal_long", widget: "string"}
      - {label: "Internal width", name: "internal_width", widget: "string"}
      - {label: "Internal height", name: "internal_height", widget: "string"}
      - {label: "Volumn", name: "volumn", widget: "string"}
      - {label: "Weight", name: "weight", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Images", name: images, widget: list, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "plasticPalletContainer"
    label: "Plastic Pallet Container"
    folder: "src/pages/plastic-pallet-containers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "plasticpalletcontainer-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "External long", name: "external_long", widget: "string"}
      - {label: "External width", name: "external_width", widget: "string"}
      - {label: "External height", name: "external_height", widget: "string"}
      - {label: "Internal long", name: "internal_long", widget: "string"}
      - {label: "Internal width", name: "internal_width", widget: "string"}
      - {label: "Internal height", name: "internal_height", widget: "string"}
      - {label: "Volumn", name: "volumn", widget: "string"}
      - {label: "Weight", name: "weight", widget: "string"}
      - {label: "Static load", name: "static_load", widget: "string"}
      - {label: "Dynamic load", name: "dynamic_load", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Images", name: images, widget: list, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
